services:
  - type: web
    name: stockoptimizer-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install --only-binary :all: -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:8000 app:app"
    envVars:
      - key: GHL_WEBHOOK_URL
        scope: run
      - key: WEBINAR_LINK
        value: https://api.leadconnectorhq.com/widget/booking/Z5TZs90rLSeZxnaP7eAu
